### ISSUE TITLE
Why is do_tests.sh in version control?

### ISSUE THREAD

**Issue by apeyser** [INM-6/nest-git-migration#2]
We have do_tests.sh.in, which would appear to be a configure input. But we also have the output in version control. Why?

**Comment by jougs** [comment]
The generated artefact `do_tests.sh` is _not_ in the SVN. This repository was created from the release 2.6.0, in which it is contained. I'll take care that it won't be in the final version of the repository.

**Comment by apeyser** [comment]
This suggests that we _not_ (oooh, markdown :8ball:)  put a flat import from the distribution directory, but that instead we do a shallow (depth 1) clone of the svn repository.

**Comment by jougs** [comment]
This was my plan from the start :-)

**Comment by apeyser** [comment]
I think then we can close issue #2... as I continue to randomly try different git hub features in some semi productive manner.
